# UAT environment - S3 backend configuration
bucket         = "terra-pipeline-tfstate"
key            = "uat/terraform.tfstate"
region         = "ap-south-1"
dynamodb_table = "terra-pipeline-tflock"
encrypt        = true
